import './profile';
import './videollamada';
import './dashboard-usuario';
import './busqueda-servicios';
import './gestion-servicios';
import './postularse-profesional';
import './gestion-usuarios';
import './agenda-profesional';
import './historial-reservas';
import './solicitudes-profesionales';
import './categorias';
import './echo';
import './paquetes-profesional'
import './explorar-paquetes';
import './notificaciones';
